### PR TITLE
Add support for new style profiler 2.8/3.0

### PR DESCRIPTION
**Pull request by layanto**

### CODE REVIEW

**Comment by layanto** [comment]
Cleaner diff
https://github.com/tedious/TedivmStashBundle/pull/90/files?w=1

**Comment by layanto** [comment]
Web debug toolbar and profiler for Symfony < 2.8 should be mostly unchanged. I based this PR on the profiler of DoctrineBundle.

**Comment by andrerom** [comment]
Code looks ok, but could you add screenshot of before and after on this PR?

**Comment by layanto** [comment]
Will do. I think I have a couple more small changes to better match styling of new profiler. Will take screenshots after.

**Comment by layanto** [comment]
Before - 2.7 - web debug toolbar (no queries)
before - 2 7 - web debug toolbar no queries

After - 2.7 - web debug toolbar (no queries)
after - 2 7 - web debug toolbar no queries

**Comment by layanto** [comment]
Before - 2.7 - web debug toolbar
before - 2 7 - web debug toolbar

After - 2.7 - web debug toolbar
after - 2 7 - web debug toolbar

**Comment by layanto** [comment]
Before - 2.7 - web debug toolbar (small)
before - 2 7 - web debug toolbar small

After - 2.7 - web debug toolbar (small)
after - 2 7 - web debug toolbar small

**Comment by layanto** [comment]
Before - 2.7 - profiler (no queries)
before - 2 7 - profiler no queries

After - 2.7 - profiler (no queries)
after - 2 7 - profiler no queries

**Comment by layanto** [comment]
Before - 2.7 - profiler
before - 2 7 - profiler

After - 2.7 - profiler
after - 2 7 - profiler

**Comment by layanto** [comment]
Before - 2.8 - web debug toolbar (no queries)
before - 2 8 - web debug toolbar no queries

After - 2.8 - web debug toolbar (no queries)
after - 2 8 - web debug toolbar no queries

**Comment by layanto** [comment]
Before - 2.8 - web debug toolbar
before - 2 8 - web debug toolbar

After - 2.8 - web debug toolbar
after - 2 8 - web debug toolbar

**Comment by layanto** [comment]
Before - 2.8 - web debug toolbar (small)
before - 2 8 - web debug toolbar small

After - 2.8 - web debug toolbar (small)
after - 2 8 - web debug toolbar small

After - 2.8 - web debug toolbar (medium)
after - 2 8 - web debug toolbar medium

**Comment by layanto** [comment]
Before - 2.8 - profiler menu (no queries)
before - 2 8 - profiler menu no queries

After - 2.8 - profiler menu (no queries)
after - 2 8 - profiler menu no queries
Note Stash icon is greyed out

**Comment by layanto** [comment]
Before - 2.8 - profiler (no queries)
before - 2 8 - profiler no queries

After - 2.8 - profiler (no queries)
after - 2 8 - profiler no queries

**Comment by layanto** [comment]
Before - 2.8 - profiler
before - 2 8 - profiler

After - 2.8 - profiler
after - 2 8 - profiler

**Comment by andrerom** [comment]
I think it looks great, so +1

> Note showing hit count in medium size view. Not sure if should show call count or hit count. Thoughts?

Well, we could show percentage hit ratio (hit/calls*100), that might be more informative and shorter number to show. Then you can optionally *(but this could also be a followup PR)* also set other colors when the ratio is particular bad. Unsure about the levels where it should kick in, but maybe yellow on less than 66% *(2/3)* and red on less than 33% *(1/3)*.

**Comment by layanto** [comment]
After - 2.8 - web debug toolbar (small)
after - 2 8 - web debug toolbar small

After - 2.8 - web debug toolbar (medium)
after - 2 8 - web debug toolbar medium

After - 2.8 - web debug toolbar
after - 2 8 - web debug toolbar

**Comment by layanto** [comment]
Ready to merge

**Comment by andrerom** [comment]
ok, +1 /cc @tedivm @jhallbachner

**Comment by tedivm** [comment]
Awesome, thanks for the pull request!

**Pull request merged**
