### PR TITLE
Able to specify custom cache item class

### PR DESCRIPTION
**Pull request by ekho**

### CODE REVIEW

**Comment by tedivm** [comment]
I like the concept and will review once tests are passing.

**Comment by ekho** [comment]
I wrote tests for CacheItemWrapper

**Comment by ekho** [comment]
up

**Comment by ekho** [comment]
@tedivm some time ago I wrote the tests and they passed. Could you make a review and merge if all ok?

**Comment by ekho** [comment]
up

**Comment by ekho** [comment]
@tedivm I just updated pull-request
Can you review it?

**Comment by ekho** [comment]
@tedivm ???

**Comment by ibrambe** [comment]
@tedivm This is the only thing I miss in the StashBundle.

**Pull request closed without merging**
